### ISSUE TITLE
Am I the only one who has these multiple errors during installation?

### ISSUE THREAD

**Issue by stojangb** [awslabs/harmonix#103] opened 2024-08-27 19:45 UTC
Many, problems, unmet dependencies, errors, script errors, etc.

Building the backstage image
====================
make[1]: Entering directory '/usr/bin/app-development-for-backstage-io-on-aws'
./build-script/build-backstage.sh
Building the backstage app...
yarn run v1.22.22
$ tsc
^[[96mpackages/backend/src/index.ts^[[0m:^[[93m147^[[0m:^[[93m13^[[0m - ^[[91merror^[[0m^[[90m TS2345: ^[[0mArgument of type 'Promise<typeof import("/usr/bin/app-development-for-backstage-io-on-aws/backstage/n>
  Type 'Promise<typeof import("/usr/bin/app-development-for-backstage-io-on-aws/backstage/node_modules/@roadiehq/catalog-backend-module-okta/dist/new-backend")>' is not assignable to type 'Promise<{ default: B>
    Type 'typeof import("/usr/bin/app-development-for-backstage-io-on-aws/backstage/node_modules/@roadiehq/catalog-backend-module-okta/dist/new-backend")' is not assignable to type '{ default: BackendFeature; >
      Types of property 'default' are incompatible.
        Type '() => BackendFeature' is not assignable to type 'BackendFeature'.
 
^[[7m147^[[0m backend.add(import('@roadiehq/catalog-backend-module-okta/new-backend'));
^[[7m   ^[[0m ^[[91m            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^[[0m
 
 
Found 1 error in packages/backend/src/index.ts^[[90m:147^[[0m
 
error Command failed with exit code 2.

[install_20240827-1523.log](https://github.com/user-attachments/files/16768073/install_20240827-1523.log)
[install_20240827-1523.log](https://github.com/user-attachments/files/16768105/install_20240827-1523.log)

**Comment by acwatson** [comment] 2024-08-28 14:48
Thanks for reporting. We are able to reproduce this and are working on a fix.

**Comment by z-sourcecode** [comment] 2024-08-28 15:14
Hi @stojangb thanks for reaching out. I did manage to replicate the issue, it seems to be a problem with @roadiehq/catalog-backend-module-okta/new-backend but we just created a fix for it in the patch. please do git pull on the latest. thanks.

**Comment by acwatson** [comment] 2024-08-28 20:44
Thanks to @z-sourcecode, this issue is now fixed. The commit that fixed it is 894064821ccdf876325559beccb62a59a705c579. We will create a new release with this fix but you can also just pull the latest from the main branch to get the fix.

**Comment by stojangb** [comment] 2024-08-28 21:40
Why was my ticket closed? Although the main issue was resolved, there are still other errors mentioned in the log file I uploaded. We have been experiencing more errors since the last update you made. We had to switch to an Ubuntu AMI for some things to work, but have you tested a full deployment of the platform? Even though some errors have been reduced, we are still seeing issues with Fargate tasks.  

Apologies if I come across as a bit harsh; I truly admire your work and appreciate the support

**Comment by z-sourcecode** [comment] 2024-08-29 00:23
HI @stojangb, We closed the ticket as the issue reported was reproduced and fixed. 
We have automated process to check every deployment on a clean installation(our workshop provisioning process), we can confirm there's no errors observed, and that we managed to get Harmonix automatically deployed and working.

Some of the errors on the log you attached relates to the applying the patch after it was already applied(no effect).
Other errors seems to be related to the runtime environment.

We build the project using: LINUX aws/codebuild/standard:6.0
https://github.com/aws/aws-codebuild-docker-images/tree/master/ubuntu/standard/6.0

I'm re-opening the ticket to make sure you resolved all the issues. Can you kindly try a clean installation and share the results? thanks!

**Comment by stojangb** [comment] 2024-08-29 18:15
This story continue in https://github.com/awslabs/harmonix/issues/105

**Closed** 2024-08-29 18:14 UTC
Labels: bug
